# Generated by Django 2.1.3 on 2018-11-09 20:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=3, verbose_name='start day')),
                ('end_day', models.CharField(choices=[('mon', 'monday'), ('tue', 'tuesday'), ('wed', 'wednesday'), ('thu', 'thursday'), ('fri', 'friday'), ('sat', 'saturday'), ('sun', 'sunday')], max_length=3, verbose_name='end day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('is_round_the_clock', models.BooleanField(default=False, verbose_name='is round the clock?')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('atm', 'ATM'), ('shop', 'Shop'), ('bank', 'Bank branch')], max_length=4, verbose_name='point type')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='coords')),
                ('is_nfc', models.BooleanField(default=False, verbose_name='is NFC?')),
                ('is_disabled_access', models.BooleanField(default=False, verbose_name='is disabled access?')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
                ('currency', models.ManyToManyField(to='currency.Currency', verbose_name='currency')),
                ('schedule', models.ManyToManyField(to='withdrawal_point.Schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATMs',
            },
        ),
    ]
