# Generated by Django 2.1.3 on 2018-11-09 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('withdrawal_point', '0003_schedule_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalpoint',
            options={'verbose_name': 'Точка выдачи наличных', 'verbose_name_plural': 'Точки выдачи наличных'},
        ),
        migrations.RemoveField(
            model_name='withdrawalpoint',
            name='currency',
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='currencies',
            field=models.ManyToManyField(to='currency.Currency', verbose_name='валюты'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_day',
            field=models.CharField(choices=[('mon', 'понедельник'), ('tue', 'вторник'), ('wed', 'среда'), ('thu', 'четверг'), ('fri', 'пятница'), ('sat', 'суббота'), ('sun', 'воскресенье')], max_length=3, verbose_name='день окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='закрыто?'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_round_the_clock',
            field=models.BooleanField(default=False, verbose_name='круглосуточно?'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_day',
            field=models.CharField(choices=[('mon', 'понедельник'), ('tue', 'вторник'), ('wed', 'среда'), ('thu', 'четверг'), ('fri', 'пятница'), ('sat', 'суббота'), ('sun', 'воскресенье')], max_length=3, verbose_name='день начала'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Bank', verbose_name='банк'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='is_disabled_access',
            field=models.NullBooleanField(default=None, verbose_name='доступно для инвалидов?'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='is_nfc',
            field=models.NullBooleanField(default=None, verbose_name='NFC?'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='point_type',
            field=models.CharField(choices=[('atm', 'банкомат'), ('shop', 'магазин'), ('bank', 'банк')], max_length=4, verbose_name='тип точки'),
        ),
        migrations.AlterField(
            model_name='withdrawalpoint',
            name='schedule',
            field=models.ManyToManyField(to='withdrawal_point.Schedule', verbose_name='расписание'),
        ),
    ]
