# Generated by Django 2.1.3 on 2018-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0005_remove_withdrawalpoint_point_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalpoint',
            name='point_type',
            field=models.IntegerField(choices=[(0, 'банкомат'), (1, 'магазин'), (2, 'банк'), (3, 'терминал')], default=0, verbose_name='тип точки'),
        ),
    ]
