# Generated by Django 2.1.3 on 2018-11-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0006_withdrawalpoint_point_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_day',
        ),
    ]
