# Generated by Django 2.1.3 on 2018-11-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0007_auto_20181110_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_day',
            field=models.IntegerField(choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], default=7, max_length=3, verbose_name='день окончания'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_day',
            field=models.IntegerField(choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], default=1, max_length=3, verbose_name='день начала'),
        ),
    ]
