# Generated by Django 2.1.3 on 2018-11-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0008_auto_20181110_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_day',
            field=models.IntegerField(choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], default=7, verbose_name='день окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_day',
            field=models.IntegerField(choices=[(1, 'понедельник'), (2, 'вторник'), (3, 'среда'), (4, 'четверг'), (5, 'пятница'), (6, 'суббота'), (7, 'воскресенье')], default=1, verbose_name='день начала'),
        ),
    ]
