# Generated by Django 2.1.3 on 2018-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0009_auto_20181110_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalpoint',
            name='is_disabled_access',
        ),
        migrations.RemoveField(
            model_name='withdrawalpoint',
            name='is_nfc',
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='cash_in',
            field=models.BooleanField(default=False, verbose_name='внесение наличных'),
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='cash_out',
            field=models.BooleanField(default=False, verbose_name='снятие наличных'),
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='contactless_payments',
            field=models.BooleanField(default=False, verbose_name='бесконтактные платежи'),
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='disabled_access',
            field=models.BooleanField(default=False, verbose_name='доступно для инвалидов'),
        ),
        migrations.AddField(
            model_name='withdrawalpoint',
            name='mobile_payments',
            field=models.BooleanField(default=False, verbose_name='мобильные устройства'),
        ),
    ]
