# Generated by Django 2.1.3 on 2018-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawal_point', '0010_auto_20181110_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalpoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес'),
        ),
    ]
