# Generated by Django 2.1.3 on 2018-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'банки', 'verbose_name_plural': 'банк'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
