# Generated by Django 2.1.3 on 2018-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20181109_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='сайт'),
        ),
    ]
