# Generated by Django 2.1.3 on 2018-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bank_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка'),
        ),
    ]
