# Generated by Django 2.1.3 on 2018-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('branch_color', models.CharField(choices=[('red', 'красная'), ('blue', 'синяя'), ('green', 'зеленая'), ('orange', 'оранжевая'), ('purple', 'фиолетовая')], max_length=16, verbose_name='ветка')),
            ],
            options={
                'verbose_name': 'станция',
                'verbose_name_plural': 'станции',
            },
        ),
    ]
